// frontend-react/src/components/app/NotificationBell.tsx
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Bell } from 'lucide-react';

import { api } from '@/lib/api';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';

interface Notif {
  id: number;
  applicant: string;
  template: string;
  when: string;
  unread: boolean;
}

const SEEN_KEY = 'ses_seen_notifications';

const getSeen = (): number[] => {
  try {
    return JSON.parse(localStorage.getItem(SEEN_KEY) || '[]');
  } catch {
    return [];
  }
};

const relative = (iso?: string): string => {
  if (!iso) return '';
  const diff = Date.now() - new Date(iso).getTime();
  const m = Math.floor(diff / 60000);
  if (m < 1) return 'hace un momento';
  if (m < 60) return `hace ${m} min`;
  const h = Math.floor(m / 60);
  if (h < 24) return `hace ${h} h`;
  return `hace ${Math.floor(h / 24)} d`;
};

/**
 * Campana de notificaciones del consultor (port de notification-bell.component.ts).
 * Deriva los estudios en estado FILLED de getApplications(); leídos en localStorage.
 */
export function NotificationBell() {
  const navigate = useNavigate();
  const [open, setOpen] = useState(false);
  const [notifs, setNotifs] = useState<Notif[]>([]);

  const reload = () => {
    api.getApplications().then((apps: any[]) => {
      const seen = getSeen();
      setNotifs(
        apps
          .filter((a) => a.status === 'FILLED')
          .map((a) => ({
            id: a.id,
            applicant:
              `${a.applicant?.first_name ?? ''} ${a.applicant?.last_name ?? ''}`.trim() ||
              a.applicant?.username ||
              'Solicitante',
            template: a.form_template?.name ?? 'Estudio',
            when: relative(a.updated_at),
            unread: !seen.includes(a.id),
          }))
          .sort((x, y) => y.id - x.id),
      );
    });
  };

  useEffect(() => {
    reload();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const unreadCount = notifs.filter((n) => n.unread).length;

  const addSeen = (id: number) => {
    const seen = Array.from(new Set([...getSeen(), id]));
    localStorage.setItem(SEEN_KEY, JSON.stringify(seen));
  };

  const markRead = (n: Notif) => {
    if (n.unread) {
      setNotifs((prev) => prev.map((x) => (x.id === n.id ? { ...x, unread: false } : x)));
      addSeen(n.id);
    }
    setOpen(false);
    navigate('/consultant');
  };

  const markAllRead = () => {
    const ids = notifs.map((n) => n.id);
    setNotifs((prev) => prev.map((n) => ({ ...n, unread: false })));
    localStorage.setItem(SEEN_KEY, JSON.stringify(Array.from(new Set([...getSeen(), ...ids]))));
  };

  return (
    <Popover
      open={open}
      onOpenChange={(o) => {
        setOpen(o);
        if (o) reload();
      }}
    >
      <PopoverTrigger asChild>
        <button
          type="button"
          aria-label="Notificaciones"
          className="relative grid h-10 w-10 place-items-center rounded-full border border-border bg-card text-foreground shadow-sm transition-colors hover:bg-accent"
        >
          <Bell className="h-[18px] w-[18px]" />
          {unreadCount > 0 && (
            <span className="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full bg-destructive px-1 text-[0.65rem] font-bold text-destructive-foreground">
              {unreadCount > 99 ? '99+' : unreadCount}
            </span>
          )}
        </button>
      </PopoverTrigger>
      <PopoverContent align="end" className="w-80 p-1">
        <div className="flex items-baseline justify-between gap-4 px-3 py-2">
          <span className="text-sm font-semibold">Notificaciones</span>
          {unreadCount > 0 && (
            <button onClick={markAllRead} className="text-xs font-medium text-primary hover:underline">
              Marcar todas como leídas
            </button>
          )}
        </div>
        <div className="my-1 h-px bg-border" />
        {notifs.map((n) => (
          <button
            key={n.id}
            onClick={() => markRead(n)}
            className="block w-full rounded-md px-3 py-2 text-left text-sm transition-colors hover:bg-accent"
          >
            <div className="relative flex items-start pe-4">
              <div className="flex-1 space-y-0.5">
                <p className="text-foreground/80">
                  <span className="font-semibold text-foreground">{n.applicant}</span> envió respuestas en{' '}
                  <span className="font-semibold text-foreground">{n.template}</span> (Folio #{n.id}).
                </p>
                <p className="text-xs text-muted-foreground">{n.when}</p>
              </div>
              {n.unread && <span className="absolute end-0 top-1.5 h-2 w-2 rounded-full bg-primary" />}
            </div>
          </button>
        ))}
        {notifs.length === 0 && (
          <p className="px-3 py-6 text-center text-sm text-muted-foreground">Sin estudios por revisar.</p>
        )}
      </PopoverContent>
    </Popover>
  );
}

// frontend/src/app/ui/notification-bell.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, Bell } from 'lucide-angular';
import { ApiService } from '../services/api.service';

interface Notif {
  id: number;
  applicant: string;
  template: string;
  when: string;
  unread: boolean;
}

/**
 * Campana de notificaciones para el consultor (adaptación del popover de 21st.dev).
 * Sin endpoint nuevo: deriva de getApplications() los estudios en estado FILLED
 * (enviados, pendientes de corroborar) y marca leídos en localStorage.
 */
@Component({
  selector: 'notification-bell',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  template: `
    <div class="relative">
      <button type="button" (click)="toggle()" aria-label="Notificaciones"
              class="relative grid h-10 w-10 place-items-center rounded-full border border-border bg-card text-foreground shadow-sm transition-colors hover:bg-accent">
        <lucide-icon [img]="BellIcon" [size]="18"></lucide-icon>
        <span *ngIf="unreadCount > 0"
              class="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full bg-destructive px-1 text-[0.65rem] font-bold text-destructive-foreground">
          {{ unreadCount > 99 ? '99+' : unreadCount }}
        </span>
      </button>

      <!-- backdrop para cerrar -->
      <div *ngIf="open" class="fixed inset-0 z-40" (click)="open = false"></div>

      <div *ngIf="open"
           class="absolute right-0 z-50 mt-2 w-80 origin-top-right rounded-xl border border-border bg-popover p-1 text-popover-foreground shadow-lg animate-in">
        <div class="flex items-baseline justify-between gap-4 px-3 py-2">
          <span class="text-sm font-semibold">Notificaciones</span>
          <button *ngIf="unreadCount > 0" (click)="markAllRead()"
                  class="text-xs font-medium text-primary hover:underline">Marcar todas como leídas</button>
        </div>
        <div class="my-1 h-px bg-border"></div>

        <div *ngFor="let n of notifs"
             (click)="markRead(n)"
             class="cursor-pointer rounded-md px-3 py-2 text-sm transition-colors hover:bg-accent">
          <div class="relative flex items-start pe-4">
            <div class="flex-1 space-y-0.5">
              <p class="text-foreground/80">
                <span class="font-semibold text-foreground">{{ n.applicant }}</span>
                envió respuestas en
                <span class="font-semibold text-foreground">{{ n.template }}</span>
                (Folio #{{ n.id }}).
              </p>
              <p class="text-xs text-muted-foreground">{{ n.when }}</p>
            </div>
            <span *ngIf="n.unread" class="absolute end-0 top-1.5 h-2 w-2 rounded-full bg-primary"></span>
          </div>
        </div>

        <p *ngIf="notifs.length === 0" class="px-3 py-6 text-center text-sm text-muted-foreground">
          Sin estudios por revisar.
        </p>
      </div>
    </div>
  `,
})
export class NotificationBellComponent implements OnInit {
  readonly BellIcon = Bell;
  open = false;
  notifs: Notif[] = [];
  private readonly seenKey = 'ses_seen_notifications';

  /** Emite el id de la aplicación al hacer clic en una notificación (para abrirla). */
  @Output() openStudy = new EventEmitter<number>();

  constructor(private api: ApiService) {}

  ngOnInit() { this.reload(); }

  get unreadCount() { return this.notifs.filter(n => n.unread).length; }

  reload() {
    this.api.getApplications().subscribe((apps: any[]) => {
      const seen = this.getSeen();
      this.notifs = apps
        .filter(a => a.status === 'FILLED')
        .map(a => ({
          id: a.id,
          applicant: `${a.applicant?.first_name ?? ''} ${a.applicant?.last_name ?? ''}`.trim() || a.applicant?.username || 'Solicitante',
          template: a.form_template?.name ?? 'Estudio',
          when: this.relative(a.updated_at),
          unread: !seen.includes(a.id),
        }))
        .sort((x, y) => y.id - x.id);
    });
  }

  toggle() {
    this.open = !this.open;
    if (this.open) this.reload();
  }

  markRead(n: Notif) {
    if (n.unread) { n.unread = false; this.addSeen(n.id); }
    this.openStudy.emit(n.id);
    this.open = false;
  }

  markAllRead() {
    const ids = this.notifs.map(n => n.id);
    this.notifs.forEach(n => n.unread = false);
    const seen = Array.from(new Set([...this.getSeen(), ...ids]));
    localStorage.setItem(this.seenKey, JSON.stringify(seen));
  }

  private getSeen(): number[] {
    try { return JSON.parse(localStorage.getItem(this.seenKey) || '[]'); } catch { return []; }
  }
  private addSeen(id: number) {
    const seen = Array.from(new Set([...this.getSeen(), id]));
    localStorage.setItem(this.seenKey, JSON.stringify(seen));
  }

  private relative(iso?: string): string {
    if (!iso) return '';
    const diff = Date.now() - new Date(iso).getTime();
    const m = Math.floor(diff / 60000);
    if (m < 1) return 'hace un momento';
    if (m < 60) return `hace ${m} min`;
    const h = Math.floor(m / 60);
    if (h < 24) return `hace ${h} h`;
    const d = Math.floor(h / 24);
    return `hace ${d} d`;
  }
}
